name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          # Build die Anwendung
          npm run build
          
          # Fix asset paths
          node <<'EOF'
          const fs = require('fs');
          const files = ['dist/index.html', 'dist/404.html'];
          
          files.forEach(file => {
            if (fs.existsSync(file)) {
              let html = fs.readFileSync(file, 'utf8');
              // Erst bestehende doppelte Pfade korrigieren
              html = html.replace(/\/abwesenheiten\/abwesenheiten\//g, '/abwesenheiten/')
                   // Dann base href setzen
                   .replace(/<base href="[^"]*"/, '<base href="/abwesenheiten/"')
                   // Dann neue Pfade setzen wenn nötig
                   .replace(/src="\//g, 'src="/abwesenheiten/')
                   .replace(/href="\//g, 'href="/abwesenheiten/')
                   // Doppelte Pfade verhindern
                   .replace(/\/abwesenheiten\/abwesenheiten\//g, '/abwesenheiten/');
              fs.writeFileSync(file, html);
            }
          });
          EOF
          
          # Copy index.html as 404.html
          cp dist/index.html dist/404.html
        env:
          VITE_BASE_URL: /abwesenheiten/
          BASE: /abwesenheiten/
          PUBLIC_URL: /abwesenheiten/
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
